# Generated by Django 4.2.13 on 2025-02-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metabolites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaboliteActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('metabolite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='metabolites.metabolite')),
            ],
        ),
    ]
