# Generated by Django 4.2.13 on 2025-02-08 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metabolites', '0002_metaboliteactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetabolitePlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_part', models.CharField(max_length=255)),
                ('low', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('deviation', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('metabolite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='metabolites.metabolite')),
            ],
        ),
    ]
